default:
  tags:
    - cognos-build

stages:
  - dco
  - osd-checks

dco:
  stage: dco
  image: christophebedard/dco-check:latest
  only:
    - merge_requests
  variables:
    GIT_SSL_NO_VERIFY: "true"
    GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    DOCKER_DRIVER: overlay2
  script:
    - |
      if [ "${CI_MERGE_REQUEST_EVENT_TYPE:-}" = detached ]; then
          git fetch -a  # so that we can resolve branch names below
          export CI_COMMIT_BRANCH="$CI_COMMIT_REF_NAME";
          export CI_MERGE_REQUEST_SOURCE_BRANCH_SHA="$(git rev-parse "origin/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME")";
          export CI_MERGE_REQUEST_TARGET_BRANCH_SHA="$(git rev-parse "origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME")";
      fi
    - dco-check

osd-checks:
  stage: osd-checks
  image: docker.corp.icr-team.com/icr/build/node:18.17.1
  only:
    - merge_requests
  script:
    - git config --global --add safe.directory /builds/cognos/OpenSearch-Dashboards
    - mkdir -p .git/hooks
    - npm install -g yarn
    - yarn osd bootstrap
    - yarn lint
